# Erste Datenqualitätsprüfung

Dieses Notebook prüft die Qualität der sieben SAP-Exporte.

## 1. Daten laden

In [1]:
from pathlib import Path
import hashlib
import re
from decimal import Decimal
import pandas as pd
try:
    from IPython.display import display
except ImportError:
    def display(value):
        print(value.to_string(index=False) if isinstance(value, pd.DataFrame) else value)

DATA_DIR = None
if DATA_DIR is None:
    candidates = [p / 'DIC_Arbeitsprobe_Testdaten_SAP_MM'
                  for p in [Path.cwd(), *Path.cwd().parents]]
    DATA_DIR = next((p for p in candidates if p.is_dir()), None)
if DATA_DIR is None or not Path(DATA_DIR).is_dir():
    raise FileNotFoundError('Set DATA_DIR to the directory containing the seven CSV files.')
DATA_DIR = Path(DATA_DIR)

spec = {
    'LFA1': ('LFA1_VENDOR_MASTER.csv', ['LIFNR']),
    'MARA': ('MARA_MATERIAL_MASTER.csv', ['MATNR']),
    'EKKO': ('EKKO_PO_HEADER.csv', ['MANDT', 'EBELN']),
    'EKPO': ('EKPO_PO_ITEM.csv', ['MANDT', 'EBELN', 'EBELP']),
    'EKET': ('EKET_SCHEDULE_LINES.csv', ['MANDT', 'EBELN', 'EBELP', 'ETENR']),
    'LIKP': ('LIKP_DELIVERY_HEADER.csv', ['MANDT', 'VBELN']),
    'LIPS': ('LIPS_DELIVERY_ITEM.csv', ['MANDT', 'VBELN', 'POSNR']),
}
raw, data, source_hashes = {}, {}, {}
for name, (filename, keys) in spec.items():
    path = DATA_DIR / filename
    source_hashes[filename] = hashlib.sha256(path.read_bytes()).hexdigest()
    frame = pd.read_csv(path, sep=';', encoding='utf-8-sig', dtype=str,
                        keep_default_na=False, na_filter=False, on_bad_lines='error')
    frame.insert(0, 'source_record', range(2, len(frame) + 2))
    raw[name] = frame
    data[name] = frame.assign(**{c: frame[c].str.strip()
                                for c in frame.columns if c != 'source_record'})

issues = {}
def show_issue(name, frame, limit=8):
    issues[name] = frame.copy()
    print(f'{name}: {len(frame)} Datensätze (maximal {limit} angezeigt)')
    display(frame.head(limit))

## 2. Tabellenübersicht und Beispieldaten

In [2]:
overview = pd.DataFrame([
    {'table': name, 'file': filename, 'rows': len(raw[name]),
     'columns': len(raw[name].columns) - 1, 'candidate_key': ', '.join(keys)}
    for name, (filename, keys) in spec.items()
])
display(overview)
for name, frame in raw.items():
    print(name)
    display(frame.head(3))

  table                      file  rows  columns               candidate_key
0  LFA1    LFA1_VENDOR_MASTER.csv    15        6                       LIFNR
1  MARA  MARA_MATERIAL_MASTER.csv    24        5                       MATNR
2  EKKO        EKKO_PO_HEADER.csv   216       12                MANDT, EBELN
3  EKPO          EKPO_PO_ITEM.csv   468       12         MANDT, EBELN, EBELP
4  EKET   EKET_SCHEDULE_LINES.csv   820        7  MANDT, EBELN, EBELP, ETENR
5  LIKP  LIKP_DELIVERY_HEADER.csv   957        6                MANDT, VBELN
6  LIPS    LIPS_DELIVERY_ITEM.csv   963        9         MANDT, VBELN, POSNR

LFA1

,source_record,LIFNR,NAME1,LAND1,ORT01,STRAS,WAERS
0,2,0000200001,Nordstein Baustoffe GmbH,DE,Hamburg,Billbrookdeich 118,EUR
1,3,0000200002,Hanse Dämmtechnik AG,DE,Lübeck,Travemünder Allee 7,EUR
2,4,0000200003,Elbe Zement & Mörtel GmbH,DE,Stade,Am Industriehafen 3,EUR

MARA

,source_record,MATNR,MAKTX,MTART,MEINS,MATKL
0,2,000000005001,"Zement CEM II/B-S 32,5 R 25 kg",HAWA,SAC,B01
1,3,000000005002,"Kalksandstein KS 2DF 12-1,8",HAWA,ST,B02
2,4,000000005003,"Porenbetonstein PP2-0,35 625x240",HAWA,ST,B02

EKKO

,source_record,MANDT,EBELN,BUKRS,BSTYP,BSART,LIFNR,EKORG,EKGRP,WAERS,BEDAT,AEDAT,ERNAM
0,2,300,4700001001,2000,F,NB,0000200006,2000,B03,EUR,2025-09-23,2025-09-23,AKOCH
1,3,300,4700001002,2000,F,NB,0000200006,2000,B03,EUR,2026-03-17,2026-03-17,SMEYER
2,4,300,4700001003,2000,F,NB,0000200004,2000,B03,EUR,2025-03-06,2025-03-06,SMEYER

EKPO

,source_record,MANDT,EBELN,EBELP,MATNR,TXZ01,MENGE,MEINS,NETPR,NETWR,WERKS,MATKL,LOEKZ
0,2,300,4700001170,00010,000000005019,"Innendispersion weiß 12,5 l",36.000,EIM,193.49,6965.64,2100,B10,
1,3,300,4700001196,00010,000000005020,Schotter 16/32 lose,26.000,TO,28.50,741.00,2100,B11,
2,4,300,4700001136,00010,000000005007,Trockenbauprofil CW 75 4000 mm,21.000,ST,58.78,1234.38,2100,B04,

EKET

   source_record MANDT       EBELN  EBELP ETENR       EINDT    MENGE    WEMNG
0              2   300  4700001195  00040  0001  2025-08-07   99.000   82.022
1              3   300  4700001176  00010  0002  2026-01-18  121.987  121.987
2              4   300  4700001076  00040  0001  2025-05-12  201.668  201.668

LIKP

   source_record MANDT       VBELN LFART       LIFNR   WADAT_IST WERKS
0              2   300  1900001001    EL  0000200006  2025-10-24  2300
1              3   300  1900001002    EL  0000200006  2025-11-06  2200
2              4   300  1900001003    EL  0000200006  2025-12-05  2200

LIPS

,source_record,MANDT,VBELN,POSNR,MATNR,LFIMG,MEINS,EBELN,EBELP,WERKS
0,2,300,1900001890,000010,000000005023,51.731,ST,4700001198,00010,2000
1,3,300,1900001340,000010,000000005015,53.450,ST,4700001080,00030,2300
2,4,300,1900001651,000010,000000005013,10.637,ROL,4700001144,00040,2200

## 3. Fehlende Werte und Leerzeichen

In [3]:
missing_rows = []
for name, frame in data.items():
    keys = spec[name][1]
    for col in frame.columns.drop('source_record'):
        blank = frame[col].eq('')
        spaces = raw[name][col].ne(frame[col])
        missing_rows.append({'table': name, 'column': col, 'key_column': col in keys,
                             'blank_rows': int(blank.sum()),
                             'blank_pct': round(100 * blank.mean(), 2),
                             'outer_whitespace_rows': int(spaces.sum())})
    show_issue(name + '_missing_key', frame.loc[frame[keys].eq('').any(axis=1)])
missing_profile = pd.DataFrame(missing_rows)
display(missing_profile)

LFA1_missing_key: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, LIFNR, NAME1, LAND1, ORT01, STRAS, WAERS]
Index: []

MARA_missing_key: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MATNR, MAKTX, MTART, MEINS, MATKL]
Index: []

EKKO_missing_key: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, EBELN, BUKRS, BSTYP, BSART, LIFNR, EKORG, EKGRP, WAERS, BEDAT, AEDAT, ERNAM]
Index: []

EKPO_missing_key: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, EBELN, EBELP, MATNR, TXZ01, MENGE, MEINS, NETPR, NETWR, WERKS, MATKL, LOEKZ]
Index: []

EKET_missing_key: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, EBELN, EBELP, ETENR, EINDT, MENGE, WEMNG]
Index: []

LIKP_missing_key: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, VBELN, LFART, LIFNR, WADAT_IST, WERKS]
Index: []

LIPS_missing_key: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, VBELN, POSNR, MATNR, LFIMG, MEINS, EBELN, EBELP, WERKS]
Index: []

   table     column  key_column  blank_rows  blank_pct  outer_whitespace_rows
0   LFA1      LIFNR        True           0       0.00                      0
1   LFA1      NAME1       False           0       0.00                      1
2   LFA1      LAND1       False           1       6.67                      0
3   LFA1      ORT01       False           0       0.00                      0
4   LFA1      STRAS       False           0       0.00                      0
5   LFA1      WAERS       False           0       0.00                      0
6   MARA      MATNR        True           0       0.00                      0
7   MARA      MAKTX       False           0       0.00                      0
8   MARA      MTART       False           0       0.00                      0
9   MARA      MEINS       False           0       0.00                      0
10  MARA      MATKL       False           0       0.00                      0
11  EKKO      MANDT        True           0       0.00                      0
12  EKKO      EBELN        True           0       0.00                      0
13  EKKO      BUKRS       False           0       0.00                      0
14  EKKO      BSTYP       False           0       0.00                      0
15  EKKO      BSART       False           0       0.00                      0
16  EKKO      LIFNR       False           0       0.00                      0
17  EKKO      EKORG       False           0       0.00                      0
18  EKKO      EKGRP       False           0       0.00                      0
19  EKKO      WAERS       False           0       0.00                      0
20  EKKO      BEDAT       False           0       0.00                      0
21  EKKO      AEDAT       False           0       0.00                      0
22  EKKO      ERNAM       False           0       0.00                      0
23  EKPO      MANDT        True           0       0.00                      0
24  EKPO      EBELN        True           0       0.00                      0
25  EKPO      EBELP        True           0       0.00                      0
26  EKPO      MATNR       False           0       0.00                      0
27  EKPO      TXZ01       False           0       0.00                     10
28  EKPO      MENGE       False           0       0.00                      0
29  EKPO      MEINS       False           0       0.00                      0
30  EKPO      NETPR       False           0       0.00                      0
31  EKPO      NETWR       False           0       0.00                      0
32  EKPO      WERKS       False           0       0.00                      0
33  EKPO      MATKL       False           0       0.00                      0
34  EKPO      LOEKZ       False         443      94.66                      0
35  EKET      MANDT        True           0       0.00                      0
36  EKET      EBELN        True           0       0.00                      0
37  EKET      EBELP        True           0       0.00                      0
38  EKET      ETENR        True           0       0.00                      0
39  EKET      EINDT       False           0       0.00                      0
40  EKET      MENGE       False           0       0.00                      0
41  EKET      WEMNG       False           0       0.00                      0
42  LIKP      MANDT        True           0       0.00                      0
43  LIKP      VBELN        True           0       0.00                      0
44  LIKP      LFART       False           0       0.00                      0
45  LIKP      LIFNR       False           0       0.00                      0
46  LIKP  WADAT_IST       False           7       0.73                      0
47  LIKP      WERKS       False           0       0.00                      0
48  LIPS      MANDT        True           0       0.00                      0
49  LIPS      VBELN        True           0       0.00                      0
50  LIPS      POSNR        True           0       0.00                      0
51  LIPS      MATNR       False           0       0.00                      0
52  LIPS      LFIMG       False           0       0.00                      0
53  LIPS      MEINS       False           0       0.00                      0
54  LIPS      EBELN       False           0       0.00                      0
55  LIPS      EBELP       False           0       0.00                      0
56  LIPS      WERKS       False           0       0.00                      0

## 4. Duplikate und Schlüsselkonflikte

In [4]:
duplicate_rows = []
for name, frame in data.items():
    keys = spec[name][1]
    fields = list(frame.columns.drop('source_record'))
    valid = frame.loc[~frame[keys].eq('').any(axis=1)]
    counts = valid.groupby(keys, dropna=False).size()
    variants = valid.drop_duplicates(fields).groupby(keys, dropna=False).size()
    conflict_keys = variants[variants > 1].reset_index()[keys]
    conflicts = valid.merge(conflict_keys, on=keys, how='inner', validate='many_to_one')
    exact = raw[name].duplicated(fields, keep=False)
    duplicate_rows.append({
        'table': name, 'exact_extra_rows_raw': int(raw[name].duplicated(fields).sum()),
        'duplicate_key_groups': int((counts > 1).sum()),
        'conflicting_key_groups': len(conflict_keys)})
    show_issue(name + '_exact_duplicates', raw[name].loc[exact])
    show_issue(name + '_key_conflicts', conflicts)
duplicate_profile = pd.DataFrame(duplicate_rows)
display(duplicate_profile)

LFA1_exact_duplicates: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, LIFNR, NAME1, LAND1, ORT01, STRAS, WAERS]
Index: []

LFA1_key_conflicts: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, LIFNR, NAME1, LAND1, ORT01, STRAS, WAERS]
Index: []

MARA_exact_duplicates: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MATNR, MAKTX, MTART, MEINS, MATKL]
Index: []

MARA_key_conflicts: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MATNR, MAKTX, MTART, MEINS, MATKL]
Index: []

EKKO_exact_duplicates: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, EBELN, BUKRS, BSTYP, BSART, LIFNR, EKORG, EKGRP, WAERS, BEDAT, AEDAT, ERNAM]
Index: []

EKKO_key_conflicts: 12 Datensätze (maximal 8 angezeigt)

,source_record,MANDT,EBELN,BUKRS,BSTYP,BSART,LIFNR,EKORG,EKGRP,WAERS,BEDAT,AEDAT,ERNAM
0,54,300,4700001053,2000,F,NB,0000200009,2000,B01,EUR,2025-03-08,2025-03-08,PWOLTER
1,60,300,4700001059,2000,F,NB,0000200012,2000,B02,DKK,2025-01-25,2025-01-25,JKRUEGER
2,73,300,4700001072,2000,F,NB,0000200008,2000,B01,EUR,2025-08-11,2025-08-11,PWOLTER
3,86,300,4700001085,2000,F,NB,0000200010,2000,B03,EUR,2026-05-02,2026-05-02,SMEYER
4,134,300,4700001133,2000,F,NB,0000200009,2000,B01,EUR,2025-08-22,2025-08-22,JKRUEGER
5,161,300,4700001160,2000,F,NB,0000200015,2000,B04,EUR,2026-02-12,2026-02-12,LHANSEN
6,212,300,4700001059,2000,F,NB,0000200012,2000,B09,DKK,2025-01-25,2025-02-02,JKRUEGER
7,213,300,4700001160,2000,F,NB,0000200015,2000,B09,EUR,2026-02-12,2026-03-03,LHANSEN

EKPO_exact_duplicates: 14 Datensätze (maximal 8 angezeigt)

,source_record,MANDT,EBELN,EBELP,MATNR,TXZ01,MENGE,MEINS,NETPR,NETWR,WERKS,MATKL,LOEKZ
33,35,300,4700001135,00020,000000005017,Innentür CPL weiß 860x1985,261.000,ST,375.07,97893.27,2200,B09,
63,65,300,4700001074,00010,000000005003,"Porenbetonstein PP2-0,35 625x240",693.000,ST,178.00,123354.00,2200,B02,
105,107,300,4700001035,00030,000000005004,Dämmplatte EPS 035 100 mm,365.000,M2,236.37,86275.05,2000,B03,L
115,117,300,4700001084,00020,000000005019,"Innendispersion weiß 12,5 l",75.000,EIM,193.49,14511.75,2100,B10,
139,141,300,4700001021,00010,000000005017,Innentür CPL weiß 860x1985,684.000,ST,375.07,256547.88,2200,B09,
214,216,300,4700001107,00040,000000005020,Schotter 16/32 lose,25.000,TO,28.50,712.50,2100,B11,
235,237,300,4700001080,00020,000000005014,KVH Konstruktionsvollholz 60x120 5 m,279.000,ST,180.11,50250.69,2000,B08,
237,239,300,4700001021,00010,000000005017,Innentür CPL weiß 860x1985,684.000,ST,375.07,256547.88,2200,B09,

EKPO_key_conflicts: 4 Datensätze (maximal 8 angezeigt)

,source_record,MANDT,EBELN,EBELP,MATNR,TXZ01,MENGE,MEINS,NETPR,NETWR,WERKS,MATKL,LOEKZ
0,63,300,4700001154,00030,000000005002,"Kalksandstein KS 2DF 12-1,8",489.000,ST,"340,05","166284,45",2300,B02,
1,147,300,4700001154,00030,000000005002,"Kalksandstein KS 2DF 12-1,8",489.000,ST,340.05,166284.45,2300,B02,
2,206,300,4700001090,00010,000000005001,"Zement CEM II/B-S 32,5 R 25 kg",1040.000,SAC,"9,80","10192,00",2300,B01,
3,221,300,4700001090,00010,000000005001,"Zement CEM II/B-S 32,5 R 25 kg",1040.000,SAC,9.80,10192.00,2300,B01,

EKET_exact_duplicates: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, EBELN, EBELP, ETENR, EINDT, MENGE, WEMNG]
Index: []

EKET_key_conflicts: 2 Datensätze (maximal 8 angezeigt)

   source_record MANDT       EBELN  EBELP ETENR       EINDT    MENGE    WEMNG
0            182   300  4700001080  00090  0001  2025-08-29  197.208  197.208
1            628   300  4700001080  00090  0001  2025-08-15   71.589   71.589

LIKP_exact_duplicates: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, VBELN, LFART, LIFNR, WADAT_IST, WERKS]
Index: []

LIKP_key_conflicts: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, VBELN, LFART, LIFNR, WADAT_IST, WERKS]
Index: []

LIPS_exact_duplicates: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, VBELN, POSNR, MATNR, LFIMG, MEINS, EBELN, EBELP, WERKS]
Index: []

LIPS_key_conflicts: 12 Datensätze (maximal 8 angezeigt)

,source_record,MANDT,VBELN,POSNR,MATNR,LFIMG,MEINS,EBELN,EBELP,WERKS
0,23,300,1900001404,000010,000000005023,11.159,ST,4700001092,00010,2100
1,81,300,1900001331,000010,000000005017,18.170,ST,4700001077,00020,2000
2,322,300,1900001429,000010,000000005013,59.000,ROL,4700001098,00010,2300
3,407,300,1900001404,000010,000000005023,12.275,ST,4700001092,00010,2100
4,497,300,1900001151,000010,000000005001,0.967,PAL,4700001041,00020,2000
5,503,300,1900001429,000010,000000005013,64.900,ROL,4700001098,00010,2300
6,655,300,1900001159,000010,000000005013,4.301,ROL,4700001043,00030,2300
7,668,300,1900001656,000010,000000005010,138.583,ST,4700001147,00020,2300

  table  exact_extra_rows_raw  duplicate_key_groups  conflicting_key_groups
0  LFA1                     0                     0                       0
1  MARA                     0                     0                       0
2  EKKO                     0                     6                       6
3  EKPO                     7                     9                       2
4  EKET                     0                     1                       1
5  LIKP                     0                     0                       0
6  LIPS                     0                     6                       6

## 5. Datumswerte

In [5]:
date_columns = {'EKKO': ['BEDAT', 'AEDAT'], 'EKET': ['EINDT'], 'LIKP': ['WADAT_IST']}
parsed_dates, date_rows = {}, []
for name, columns in date_columns.items():
    for col in columns:
        values = data[name][col]
        shape = values.str.fullmatch(r'\d{4}-\d{2}-\d{2}')
        parsed = pd.to_datetime(values.where(shape), format='%Y-%m-%d', errors='coerce')
        parsed_dates[name, col] = parsed
        bad = values.ne('') & parsed.isna()
        date_rows.append({'table': name, 'column': col, 'missing': int(values.eq('').sum()),
                          'invalid_nonblank': int(bad.sum()), 'min': parsed.min(), 'max': parsed.max()})
        show_issue(name + '_' + col + '_invalid_date', data[name].loc[bad])
date_profile = pd.DataFrame(date_rows)
display(date_profile)
changed_before_created = parsed_dates['EKKO', 'AEDAT'] < parsed_dates['EKKO', 'BEDAT']
show_issue('EKKO_change_before_order_date', data['EKKO'].loc[changed_before_created])

EKKO_BEDAT_invalid_date: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, EBELN, BUKRS, BSTYP, BSART, LIFNR, EKORG, EKGRP, WAERS, BEDAT, AEDAT, ERNAM]
Index: []

EKKO_AEDAT_invalid_date: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, EBELN, BUKRS, BSTYP, BSART, LIFNR, EKORG, EKGRP, WAERS, BEDAT, AEDAT, ERNAM]
Index: []

EKET_EINDT_invalid_date: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, EBELN, EBELP, ETENR, EINDT, MENGE, WEMNG]
Index: []

LIKP_WADAT_IST_invalid_date: 35 Datensätze (maximal 8 angezeigt)

     source_record MANDT       VBELN LFART       LIFNR   WADAT_IST WERKS
26              28   300  1900001027    EL  0000200009  27.07.2025  2100
37              39   300  1900001038    EL  0000200015  06.07.2025  2300
98             100   300  1900001099    EL  0000200011  15.09.2025  2000
103            105   300  1900001104    EL  0000200007  31.07.2025  2100
122            124   300  1900001123    EL  0000200011  12.01.2026  2300
132            134   300  1900001133    EL  0000200002  20.06.2026  2200
136            138   300  1900001137    EL  0000200004  07.09.2025  2200
143            145   300  1900001144    EL  0000200010  17.12.2025  2300

  table     column  missing  invalid_nonblank        min        max
0  EKKO      BEDAT        0                 0 2025-01-09 2026-06-30
1  EKKO      AEDAT        0                 0 2025-01-09 2026-06-30
2  EKET      EINDT        0                 0 2025-01-21 2026-09-06
3  LIKP  WADAT_IST        7                35 2025-01-20 2026-09-06

EKKO_change_before_order_date: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, EBELN, BUKRS, BSTYP, BSART, LIFNR, EKORG, EKGRP, WAERS, BEDAT, AEDAT, ERNAM]
Index: []

## 6. Mengen und Beträge

In [6]:
numeric_columns = {'EKPO': ['MENGE', 'NETPR', 'NETWR'],
                   'EKET': ['MENGE', 'WEMNG'], 'LIPS': ['LFIMG']}
numbers, numeric_rows = {}, []
for name, columns in numeric_columns.items():
    for col in columns:
        values = data[name][col]
        valid = values.str.fullmatch(r'[+-]?\d+(?:\.\d+)?')
        parsed = values.map(lambda value: Decimal(value) if re.fullmatch(r'[+-]?\d+(?:\.\d+)?', value) else None)
        numbers[name, col] = parsed
        negative = parsed.map(lambda value: value is not None and value < 0)
        zero = parsed.map(lambda value: value is not None and value == 0)
        invalid = values.ne('') & ~valid
        good = parsed.dropna()
        numeric_rows.append({'table': name, 'column': col, 'missing': int(values.eq('').sum()),
                             'invalid_nonblank': int(invalid.sum()), 'negative': int(negative.sum()),
                             'zero': int(zero.sum()), 'min': str(good.min()) if len(good) else None,
                             'max': str(good.max()) if len(good) else None})
        show_issue(name + '_' + col + '_invalid_number', data[name].loc[invalid])
        show_issue(name + '_' + col + '_negative', data[name].loc[negative])
numeric_profile = pd.DataFrame(numeric_rows)
display(numeric_profile)
over_received = pd.Series([a is not None and b is not None and a > b
                          for a, b in zip(numbers['EKET', 'WEMNG'], numbers['EKET', 'MENGE'])],
                         index=data['EKET'].index)
show_issue('EKET_received_above_scheduled_review', data['EKET'].loc[over_received])

EKPO_MENGE_invalid_number: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, EBELN, EBELP, MATNR, TXZ01, MENGE, MEINS, NETPR, NETWR, WERKS, MATKL, LOEKZ]
Index: []

EKPO_MENGE_negative: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, EBELN, EBELP, MATNR, TXZ01, MENGE, MEINS, NETPR, NETWR, WERKS, MATKL, LOEKZ]
Index: []

EKPO_NETPR_invalid_number: 22 Datensätze (maximal 8 angezeigt)

,source_record,MANDT,EBELN,EBELP,MATNR,TXZ01,MENGE,MEINS,NETPR,NETWR,WERKS,MATKL,LOEKZ
7,9,300,4700001058,00030,000000005007,Trockenbauprofil CW 75 4000 mm,689.000,ST,"58,78","40499,42",2000,B04,
32,34,300,4700001055,00020,000000005008,Bodenfliese Feinsteinzeug 60x60 grau,778.000,M2,"66,90","52048,20",2300,B05,
60,62,300,4700001184,00030,000000005008,Bodenfliese Feinsteinzeug 60x60 grau,82.000,M2,"66,90","5485,80",2000,B05,
61,63,300,4700001154,00030,000000005002,"Kalksandstein KS 2DF 12-1,8",489.000,ST,"340,05","166284,45",2300,B02,
94,96,300,4700001100,00030,000000005009,Fugenmörtel flexibel 25 kg,827.000,SAC,"178,30","147454,10",2000,B05,
104,106,300,4700001144,00030,000000005012,Dachziegel Tondach rot,239.000,ST,"113,53","27133,67",2200,B07,
176,178,300,4700001208,00040,000000005011,Baustahlmatte Q188A,240.000,ST,"97,92","23500,80",2100,B06,
201,203,300,4700001062,00020,000000005004,Dämmplatte EPS 035 100 mm,622.000,M2,"236,37","147022,14",2200,B03,

EKPO_NETPR_negative: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, EBELN, EBELP, MATNR, TXZ01, MENGE, MEINS, NETPR, NETWR, WERKS, MATKL, LOEKZ]
Index: []

EKPO_NETWR_invalid_number: 22 Datensätze (maximal 8 angezeigt)

,source_record,MANDT,EBELN,EBELP,MATNR,TXZ01,MENGE,MEINS,NETPR,NETWR,WERKS,MATKL,LOEKZ
7,9,300,4700001058,00030,000000005007,Trockenbauprofil CW 75 4000 mm,689.000,ST,"58,78","40499,42",2000,B04,
32,34,300,4700001055,00020,000000005008,Bodenfliese Feinsteinzeug 60x60 grau,778.000,M2,"66,90","52048,20",2300,B05,
60,62,300,4700001184,00030,000000005008,Bodenfliese Feinsteinzeug 60x60 grau,82.000,M2,"66,90","5485,80",2000,B05,
61,63,300,4700001154,00030,000000005002,"Kalksandstein KS 2DF 12-1,8",489.000,ST,"340,05","166284,45",2300,B02,
94,96,300,4700001100,00030,000000005009,Fugenmörtel flexibel 25 kg,827.000,SAC,"178,30","147454,10",2000,B05,
104,106,300,4700001144,00030,000000005012,Dachziegel Tondach rot,239.000,ST,"113,53","27133,67",2200,B07,
176,178,300,4700001208,00040,000000005011,Baustahlmatte Q188A,240.000,ST,"97,92","23500,80",2100,B06,
201,203,300,4700001062,00020,000000005004,Dämmplatte EPS 035 100 mm,622.000,M2,"236,37","147022,14",2200,B03,

EKPO_NETWR_negative: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, EBELN, EBELP, MATNR, TXZ01, MENGE, MEINS, NETPR, NETWR, WERKS, MATKL, LOEKZ]
Index: []

EKET_MENGE_invalid_number: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, EBELN, EBELP, ETENR, EINDT, MENGE, WEMNG]
Index: []

EKET_MENGE_negative: 3 Datensätze (maximal 8 angezeigt)

,source_record,MANDT,EBELN,EBELP,ETENR,EINDT,MENGE,WEMNG
221,223,300,4700001210,00090,0001,2025-05-04,-43.721,43.721
498,500,300,4700001085,00010,0001,2026-05-13,-549.000,549.000
608,610,300,4700001123,00010,0002,2026-08-06,-82.243,82.243

EKET_WEMNG_invalid_number: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, EBELN, EBELP, ETENR, EINDT, MENGE, WEMNG]
Index: []

EKET_WEMNG_negative: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, EBELN, EBELP, ETENR, EINDT, MENGE, WEMNG]
Index: []

LIPS_LFIMG_invalid_number: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, VBELN, POSNR, MATNR, LFIMG, MEINS, EBELN, EBELP, WERKS]
Index: []

LIPS_LFIMG_negative: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, VBELN, POSNR, MATNR, LFIMG, MEINS, EBELN, EBELP, WERKS]
Index: []

  table column  missing  invalid_nonblank  negative  zero       min        max
0  EKPO  MENGE        0                 0         0     2     0.000   1183.000
1  EKPO  NETPR        0                22         0     0      9.80     489.00
2  EKPO  NETWR        0                22         0     2      0.00  485210.70
3  EKET  MENGE        0                 0         3     0  -549.000   1183.000
4  EKET  WEMNG        0                 0         0    62     0.000   1183.000
5  LIPS  LFIMG        0                 0         0     0     0.189   1183.000

EKET_received_above_scheduled_review: 24 Datensätze (maximal 8 angezeigt)

,source_record,MANDT,EBELN,EBELP,ETENR,EINDT,MENGE,WEMNG
16,18,300,4700001068,00010,0001,2025-07-11,103.000,112.036
76,78,300,4700001055,00010,0001,2025-11-29,915.000,1033.762
194,196,300,4700001059,00030,0001,2025-02-26,805.000,923.634
221,223,300,4700001210,00090,0001,2025-05-04,-43.721,43.721
233,235,300,4700001100,00010,0001,2025-03-02,217.862,242.828
265,267,300,4700001058,00030,0002,2026-03-24,637.013,690.909
272,274,300,4700001069,00020,0001,2026-06-01,811.000,908.864
277,279,300,4700001016,00010,0001,2026-05-14,120.672,136.393

## 7. Tabellenbeziehungen

In [7]:
relations = [
    ('EKPO', 'EKKO', ['MANDT', 'EBELN']),
    ('EKET', 'EKPO', ['MANDT', 'EBELN', 'EBELP']),
    ('LIPS', 'EKPO', ['MANDT', 'EBELN', 'EBELP']),
    ('LIPS', 'LIKP', ['MANDT', 'VBELN']),
    ('EKKO', 'LFA1', ['LIFNR']), ('LIKP', 'LFA1', ['LIFNR']),
    ('EKPO', 'MARA', ['MATNR']), ('LIPS', 'MARA', ['MATNR']),
]
relation_rows = []
for child_name, parent_name, keys in relations:
    child, parent = data[child_name], data[parent_name]
    blank = child[keys].eq('').any(axis=1)
    parent_valid = parent.loc[~parent[keys].eq('').any(axis=1)]
    parent_counts = parent_valid.groupby(keys).size().rename('parent_rows').reset_index()
    joined = child.loc[~blank].merge(parent_counts, on=keys, how='left', validate='many_to_one')
    missing = joined.loc[joined['parent_rows'].isna()]
    ambiguous = joined.loc[joined['parent_rows'].gt(1)]
    label = child_name + '_to_' + parent_name
    relation_rows.append({'relationship': label, 'child_rows': len(child),
                          'blank_reference_rows': int(blank.sum()), 'missing_parent_rows': len(missing),
                          'ambiguous_parent_rows': len(ambiguous)})
    show_issue(label + '_missing_parent', missing)
    show_issue(label + '_ambiguous_parent', ambiguous)
relation_profile = pd.DataFrame(relation_rows)
display(relation_profile)

EKPO_to_EKKO_missing_parent: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, EBELN, EBELP, MATNR, TXZ01, MENGE, MEINS, NETPR, NETWR, WERKS, MATKL, LOEKZ, parent_rows]
Index: []

EKPO_to_EKKO_ambiguous_parent: 13 Datensätze (maximal 8 angezeigt)

     source_record MANDT       EBELN  EBELP  ... WERKS MATKL LOEKZ parent_rows
35              37   300  4700001160  00020  ...  2200   B02                 2
70              72   300  4700001072  00010  ...  2200   B06                 2
122            124   300  4700001059  00030  ...  2200   B03                 2
131            133   300  4700001133  00010  ...  2200   B12                 2
143            145   300  4700001053  00010  ...  2300   B12                 2
156            158   300  4700001160  00030  ...  2200   B01                 2
166            168   300  4700001160  00010  ...  2100   B01                 2
197            199   300  4700001059  00010  ...  2200   B03     L           2

[8 rows x 14 columns]

EKET_to_EKPO_missing_parent: 5 Datensätze (maximal 8 angezeigt)

     source_record MANDT       EBELN  ...    MENGE    WEMNG parent_rows
180            182   300  4700001080  ...  197.208  197.208         NaN
221            223   300  4700001210  ...  -43.721   43.721         NaN
527            529   300  4700001051  ...  339.000  339.000         NaN
626            628   300  4700001080  ...   71.589   71.589         NaN
693            695   300  4700001063  ...  626.002  626.002         NaN

[5 rows x 9 columns]

EKET_to_EKPO_ambiguous_parent: 18 Datensätze (maximal 8 angezeigt)

     source_record MANDT       EBELN  ...    MENGE    WEMNG parent_rows
17              19   300  4700001080  ...   81.792   81.792         2.0
39              41   300  4700001090  ...   46.538   46.538         2.0
65              67   300  4700001035  ...  365.000    0.000         2.0
232            234   300  4700001154  ...   88.450   88.450         2.0
304            306   300  4700001084  ...   18.344   18.344         2.0
312            314   300  4700001021  ...  684.000  684.000         2.0
360            362   300  4700001074  ...  457.391    0.000         2.0
438            440   300  4700001107  ...   25.000   25.000         2.0

[8 rows x 9 columns]

LIPS_to_EKPO_missing_parent: 7 Datensätze (maximal 8 angezeigt)

     source_record MANDT       VBELN  ...  EBELP WERKS parent_rows
177            179   300  1900001957  ...  00020  2100         NaN
407            409   300  1900001954  ...  00020  2300         NaN
591            593   300  1900001953  ...  00010  2000         NaN
614            616   300  1900001952  ...  00010  2000         NaN
777            779   300  1900001951  ...  00040  2000         NaN
783            785   300  1900001955  ...  00020  2000         NaN
843            845   300  1900001956  ...  00020  2000         NaN

[7 rows x 11 columns]

LIPS_to_EKPO_ambiguous_parent: 21 Datensätze (maximal 8 angezeigt)

     source_record MANDT       VBELN  ...  EBELP WERKS parent_rows
46              48   300  1900001706  ...  00030  2300         2.0
82              84   300  1900001469  ...  00040  2100         2.0
101            103   300  1900001399  ...  00010  2300         2.0
175            177   300  1900001315  ...  00010  2200         2.0
182            184   300  1900001314  ...  00010  2200         2.0
250            252   300  1900001705  ...  00030  2300         2.0
317            319   300  1900001395  ...  00010  2300         2.0
324            326   300  1900001396  ...  00010  2300         2.0

[8 rows x 11 columns]

LIPS_to_LIKP_missing_parent: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, VBELN, POSNR, MATNR, LFIMG, MEINS, EBELN, EBELP, WERKS, parent_rows]
Index: []

LIPS_to_LIKP_ambiguous_parent: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, VBELN, POSNR, MATNR, LFIMG, MEINS, EBELN, EBELP, WERKS, parent_rows]
Index: []

EKKO_to_LFA1_missing_parent: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, EBELN, BUKRS, BSTYP, BSART, LIFNR, EKORG, EKGRP, WAERS, BEDAT, AEDAT, ERNAM, parent_rows]
Index: []

EKKO_to_LFA1_ambiguous_parent: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, EBELN, BUKRS, BSTYP, BSART, LIFNR, EKORG, EKGRP, WAERS, BEDAT, AEDAT, ERNAM, parent_rows]
Index: []

LIKP_to_LFA1_missing_parent: 28 Datensätze (maximal 8 angezeigt)

     source_record MANDT       VBELN  ...   WADAT_IST WERKS parent_rows
28              30   300  1900001029  ...  2025-03-30  2200         NaN
43              45   300  1900001044  ...  2026-07-01  2200         NaN
50              52   300  1900001051  ...  2025-09-24  2300         NaN
119            121   300  1900001120  ...  2026-02-03  2200         NaN
155            157   300  1900001156  ...  2026-03-13  2000         NaN
158            160   300  1900001159  ...  2026-03-17  2300         NaN
183            185   300  1900001184  ...  2026-04-14  2200         NaN
207            209   300  1900001208  ...  2025-03-14  2000         NaN

[8 rows x 8 columns]

LIKP_to_LFA1_ambiguous_parent: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, VBELN, LFART, LIFNR, WADAT_IST, WERKS, parent_rows]
Index: []

EKPO_to_MARA_missing_parent: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, EBELN, EBELP, MATNR, TXZ01, MENGE, MEINS, NETPR, NETWR, WERKS, MATKL, LOEKZ, parent_rows]
Index: []

EKPO_to_MARA_ambiguous_parent: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, EBELN, EBELP, MATNR, TXZ01, MENGE, MEINS, NETPR, NETWR, WERKS, MATKL, LOEKZ, parent_rows]
Index: []

LIPS_to_MARA_missing_parent: 25 Datensätze (maximal 8 angezeigt)

     source_record MANDT       VBELN  ...  EBELP WERKS parent_rows
8               10   300  1900001383  ...  00030  2300         NaN
25              27   300  1900001175  ...  00040  2300         NaN
27              29   300  1900001053  ...  00020  2200         NaN
74              76   300  1900001477  ...  00030  2200         NaN
127            129   300  1900001680  ...  00010  2300         NaN
177            179   300  1900001957  ...  00020  2100         NaN
194            196   300  1900001784  ...  00030  2200         NaN
219            221   300  1900001818  ...  00010  2100         NaN

[8 rows x 11 columns]

LIPS_to_MARA_ambiguous_parent: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, VBELN, POSNR, MATNR, LFIMG, MEINS, EBELN, EBELP, WERKS, parent_rows]
Index: []

   relationship  child_rows  ...  missing_parent_rows  ambiguous_parent_rows
0  EKPO_to_EKKO         468  ...                    0                     13
1  EKET_to_EKPO         820  ...                    5                     18
2  LIPS_to_EKPO         963  ...                    7                     21
3  LIPS_to_LIKP         963  ...                    0                      0
4  EKKO_to_LFA1         216  ...                    0                      0
5  LIKP_to_LFA1         957  ...                   28                      0
6  EKPO_to_MARA         468  ...                    0                      0
7  LIPS_to_MARA         963  ...                   25                      0

[8 rows x 5 columns]

## 8. Einheiten, Materialien und Niederlassungen

In [8]:
comparison_rows = []
def compare_fields(child_name, parent_name, keys, fields):
    child, parent = data[child_name], data[parent_name]
    valid_parent = parent.loc[~parent[keys].eq('').any(axis=1)]
    unique_parent = valid_parent.loc[~valid_parent.duplicated(keys, keep=False)]
    right = unique_parent[keys + fields].rename(columns={c: 'parent_' + c for c in fields})
    merged = child.loc[~child[keys].eq('').any(axis=1)].merge(
        right, on=keys, how='inner', validate='many_to_one')
    for col in fields:
        comparable = merged[col].ne('') & merged['parent_' + col].ne('')
        mismatch = comparable & merged[col].ne(merged['parent_' + col])
        label = f'{child_name}_to_{parent_name}_{col}'
        comparison_rows.append({'check': label, 'child_rows': len(child),
                                'compared_rows': int(comparable.sum()),
                                'not_compared_rows': len(child) - int(comparable.sum()),
                                'mismatch_rows': int(mismatch.sum())})
        show_issue(label + '_mismatch', merged.loc[mismatch])

compare_fields('EKPO', 'MARA', ['MATNR'], ['MEINS'])
compare_fields('LIPS', 'MARA', ['MATNR'], ['MEINS'])
compare_fields('LIPS', 'EKPO', ['MANDT', 'EBELN', 'EBELP'], ['MEINS', 'MATNR', 'WERKS'])
compare_fields('LIPS', 'LIKP', ['MANDT', 'VBELN'], ['WERKS'])
comparison_profile = pd.DataFrame(comparison_rows)
display(comparison_profile)
for name, col in [('EKPO', 'MEINS'), ('LIPS', 'MEINS'), ('EKPO', 'LOEKZ'),
                  ('EKPO', 'WERKS'), ('LIKP', 'WERKS'), ('LIPS', 'WERKS')]:
    print(name, col)
    display(data[name][col].value_counts(dropna=False).rename_axis(col).reset_index(name='rows'))

EKPO_to_MARA_MEINS_mismatch: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, EBELN, EBELP, MATNR, TXZ01, MENGE, MEINS, NETPR, NETWR, WERKS, MATKL, LOEKZ, parent_MEINS]
Index: []

LIPS_to_MARA_MEINS_mismatch: 9 Datensätze (maximal 8 angezeigt)

,source_record,MANDT,VBELN,POSNR,MATNR,LFIMG,MEINS,EBELN,EBELP,WERKS,parent_MEINS
201,210,300,1900001038,000010,000000005001,11.604,PAL,4700001011,00010,2300,SAC
205,214,300,1900001152,000010,000000005001,2.966,PAL,4700001041,00020,2000,SAC
263,273,300,1900001040,000010,000000005001,0.189,PAL,4700001011,00010,2300,SAC
283,293,300,1900001030,000010,000000005001,1.590,PAL,4700001009,00020,2200,SAC
286,296,300,1900001039,000010,000000005001,6.311,PAL,4700001011,00010,2300,SAC
401,413,300,1900001153,000010,000000005001,2.021,PAL,4700001042,00010,2300,SAC
480,497,300,1900001151,000010,000000005001,0.967,PAL,4700001041,00020,2000,SAC
509,527,300,1900001154,000010,000000005001,3.308,PAL,4700001042,00010,2300,SAC

LIPS_to_EKPO_MEINS_mismatch: 9 Datensätze (maximal 8 angezeigt)

,source_record,MANDT,VBELN,POSNR,MATNR,LFIMG,MEINS,EBELN,EBELP,WERKS,parent_MEINS,parent_MATNR,parent_WERKS
202,210,300,1900001038,000010,000000005001,11.604,PAL,4700001011,00010,2300,SAC,000000005001,2300
206,214,300,1900001152,000010,000000005001,2.966,PAL,4700001041,00020,2000,SAC,000000005001,2000
264,273,300,1900001040,000010,000000005001,0.189,PAL,4700001011,00010,2300,SAC,000000005001,2300
284,293,300,1900001030,000010,000000005001,1.590,PAL,4700001009,00020,2200,SAC,000000005001,2200
287,296,300,1900001039,000010,000000005001,6.311,PAL,4700001011,00010,2300,SAC,000000005001,2300
399,413,300,1900001153,000010,000000005001,2.021,PAL,4700001042,00010,2300,SAC,000000005001,2300
480,497,300,1900001151,000010,000000005001,0.967,PAL,4700001041,00020,2000,SAC,000000005001,2000
509,527,300,1900001154,000010,000000005001,3.308,PAL,4700001042,00010,2300,SAC,000000005001,2300

LIPS_to_EKPO_MATNR_mismatch: 22 Datensätze (maximal 8 angezeigt)

,source_record,MANDT,VBELN,POSNR,MATNR,LFIMG,MEINS,EBELN,EBELP,WERKS,parent_MEINS,parent_MATNR,parent_WERKS
8,10,300,1900001383,000010,5016,164.443,ST,4700001087,00030,2300,ST,000000005016,2300
25,27,300,1900001175,000010,5022,102.243,M2,4700001047,00040,2300,M2,000000005022,2300
27,29,300,1900001053,000010,5018,43.713,EIM,4700001014,00020,2200,EIM,000000005018,2200
73,76,300,1900001477,000010,5009,301.653,SAC,4700001108,00030,2200,SAC,000000005009,2200
124,129,300,1900001680,000010,5016,36.289,ST,4700001152,00010,2300,ST,000000005016,2300
188,196,300,1900001784,000010,5003,290.413,ST,4700001172,00030,2200,ST,000000005003,2200
213,221,300,1900001818,000010,5023,738.000,ST,4700001182,00010,2100,ST,000000005023,2100
353,365,300,1900001923,000010,5010,145.450,ST,4700001204,00010,2300,ST,000000005010,2300

LIPS_to_EKPO_WERKS_mismatch: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, VBELN, POSNR, MATNR, LFIMG, MEINS, EBELN, EBELP, WERKS, parent_MEINS, parent_MATNR, parent_WERKS]
Index: []

LIPS_to_LIKP_WERKS_mismatch: 0 Datensätze (maximal 8 angezeigt)

Empty DataFrame
Columns: [source_record, MANDT, VBELN, POSNR, MATNR, LFIMG, MEINS, EBELN, EBELP, WERKS, parent_WERKS]
Index: []

,check,child_rows,compared_rows,not_compared_rows,mismatch_rows
0,EKPO_to_MARA_MEINS,468,468,0,0
1,LIPS_to_MARA_MEINS,963,938,25,9
2,LIPS_to_EKPO_MEINS,963,935,28,9
3,LIPS_to_EKPO_MATNR,963,935,28,22
4,LIPS_to_EKPO_WERKS,963,935,28,0
5,LIPS_to_LIKP_WERKS,963,963,0,0

EKPO MEINS

  MEINS  rows
0    ST   219
1    M2   103
2   SAC    76
3    TO    30
4   EIM    21
5   ROL    19

LIPS MEINS

  MEINS  rows
0    ST   475
1    M2   188
2   SAC   153
3    TO    62
4   ROL    39
5   EIM    37
6   PAL     9

EKPO LOEKZ

  LOEKZ  rows
0         443
1     L    25

EKPO WERKS

  WERKS  rows
0  2100   126
1  2200   126
2  2000   112
3  2300   104

LIKP WERKS

  WERKS  rows
0  2200   259
1  2100   251
2  2300   225
3  2000   222

LIPS WERKS

  WERKS  rows
0  2200   259
1  2100   252
2  2300   228
3  2000   224

## 9. Mehrfachzuordnungen beim Join

In [9]:
item_key = ['MANDT', 'EBELN', 'EBELP']
schedule_counts = data['EKET'].groupby(item_key).size().rename('schedule_rows')
delivery_counts = data['LIPS'].groupby(item_key).size().rename('delivery_rows')
fanout = schedule_counts.to_frame().join(delivery_counts, how='inner').reset_index()
fanout['naive_join_rows'] = fanout['schedule_rows'] * fanout['delivery_rows']
fanout = fanout.loc[(fanout['schedule_rows'] > 1) & (fanout['delivery_rows'] > 1)]
show_issue('schedule_delivery_many_to_many', fanout.sort_values('naive_join_rows', ascending=False))

schedule_delivery_many_to_many: 243 Datensätze (maximal 8 angezeigt)

    MANDT       EBELN  EBELP  schedule_rows  delivery_rows  naive_join_rows
194   300  4700001095  00010              3              6               18
322   300  4700001153  00020              3              6               18
98    300  4700001052  00010              3              5               15
131   300  4700001064  00010              3              5               15
205   300  4700001099  00030              3              5               15
187   300  4700001090  00010              3              5               15
190   300  4700001092  00010              3              5               15
179   300  4700001086  00010              3              5               15

## 10. Ergebnisse

In [10]:
findings = pd.DataFrame([{'check': name, 'records': len(frame)}
                         for name, frame in issues.items() if len(frame)])
if len(findings):
    display(findings.sort_values(['records', 'check'], ascending=[False, True]).reset_index(drop=True))
else:
    print('Keine Auffälligkeiten gefunden.')


assert all(hashlib.sha256((DATA_DIR / filename).read_bytes()).hexdigest() == digest
           for filename, digest in source_hashes.items()), 'A source file changed during execution.'
print('Quelldateien unverändert.')

                                   check  records
0         schedule_delivery_many_to_many      243
1            LIKP_WADAT_IST_invalid_date       35
2            LIKP_to_LFA1_missing_parent       28
3            LIPS_to_MARA_missing_parent       25
4   EKET_received_above_scheduled_review       24
5              EKPO_NETPR_invalid_number       22
6              EKPO_NETWR_invalid_number       22
7            LIPS_to_EKPO_MATNR_mismatch       22
8          LIPS_to_EKPO_ambiguous_parent       21
9          EKET_to_EKPO_ambiguous_parent       18
10                 EKPO_exact_duplicates       14
11         EKPO_to_EKKO_ambiguous_parent       13
12                    EKKO_key_conflicts       12
13                    LIPS_key_conflicts       12
14           LIPS_to_EKPO_MEINS_mismatch        9
15           LIPS_to_MARA_MEINS_mismatch        9
16           LIPS_to_EKPO_missing_parent        7
17           EKET_to_EKPO_missing_parent        5
18                    EKPO_key_conflicts        4
19                   EKET_MENGE_negative        3
20                    EKET_key_conflicts        2

Quelldateien unverändert.